### ISSUE TITLE
Delay to crawl

### ISSUE THREAD

**Issue by herlon214** [missinglink/huntsman#14]
Hi everyone, I was crawling a website and it shows a error message if I acess X pages in Y secounds. Have any possibility to do a delay feature?
Sorry for the noob question. But I don't know if the throttle plugin do this.

**Comment by missinglink** [comment]
hey @herlon214 have a look at the `throttle` setting in the docs here: https://github.com/missinglink/huntsman#configuration

**Comment by herlon214** [comment]
But, can I use less than one request per second?

Em sexta-feira, 31 de julho de 2015, Peter Johnson a.k.a. insertcoffee <
notifications@github.com> escreveu:

> hey @herlon214 <https://github.com/herlon214> have a look at the throttle
> setting in the docs here:
> https://github.com/missinglink/huntsman#configuration
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/missinglink/huntsman/issues/14#issuecomment-126685530>
> .
>


-- 
*Att, Herlon Aguiar*

**Comment by missinglink** [comment]
yep, if you set it to `throttle: 0.5` then it should only make one request every `2 seconds` or use `0.2` for once every `5 seconds` etc.

**Comment by missinglink** [comment]
if you are waiting that long between requests you should also increase `timeout` to something like `30000` (30 secs)

**Comment by herlon214** [comment]
Thanks!
